;=============================================================================
; @file obfuscation_16.inc
;
; Some obfuscation methods for 16 bit application. 
;
; Copyright 2017 Hamidreza Ebtehaj.
; Use of this source code is governed by a BSD-style license that can
; be found in the LICENSE file.
;=============================================================================

%ifndef __CRACKME_OBFUSCATION_16_INC__
%define __CRACKME_OBFUSCATION_16_INC__


%endif