;=============================================================================
; @file rc6_32.inc
;
; It is the implementation of RC4 algorithm for Win32.
;
; Copyright 2017 Hamidreza Ebtehaj.
; Use of this source code is governed by a BSD-style license that can
; be found in the LICENSE file.
;=============================================================================

%ifndef __CRACKME_RC4_32_INC__
%define __CRACKME_RC4_32_INC__

%macro  RC4_32 0
    
%endmacro

%endif